name: minime
description: "MiniMe - personal organizer app pentru Home / Work / Personal"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # persistenta locala
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # utilitare
  intl: ^0.19.0
  uuid: ^4.2.1
  provider: ^6.1.1

  # notificari, voce, culori
  flutter_local_notifications: ^17.0.0
  flutter_tts: ^4.0.2
  flutter_colorpicker: ^1.0.3
  timezone: ^0.9.2

  # Faza 6: profile export, home screen widget, location reminders
  share_plus: ^7.2.1
  home_widget: ^0.6.0
  geolocator: ^11.0.0

  # Faza 3: calendar in-app
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
